server {
  listen 80;
  server_name _;

  # статика CRA
  root /usr/share/nginx/html;
  index index.html;

  # сжатие
  gzip on;
  gzip_types text/plain text/css application/json application/javascript application/xml+rss application/xml text/javascript image/svg+xml;

  # отдаём файл, если существует, иначе index.html (SPA)
  location / {
    try_files $uri /index.html;
  }

  # можно проксировать /api на бэк, если захочешь убрать абсолютные URL во фронте
  # location /api/ {
  #   proxy_pass http://backend:5000/;
  #   proxy_http_version 1.1;
  #   proxy_set_header Upgrade $http_upgrade;
  #   proxy_set_header Connection "upgrade";
  #   proxy_set_header Host $host;
  #   proxy_set_header X-Real-IP $remote_addr;
  # }
}
