stages: [test, build, deploy]

test:
  image: python:3.12
  script:
    - pytest --cov=app
  coverage: '/TOTAL.*\s([0-9]{1,3})%/'

build:
  image: docker:dind
  script:
    - docker build -t registry/teamforge:$CI_COMMIT_SHA .

deploy:
  stage: deploy
  script:
    - helm upgrade --install teamforge chart/ --set image.tag=$CI_COMMIT_SHA
