version: '3.8'
services:
  backend:
    build: ./backend
    container_name: messenger_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    restart: always

  frontend:
    build: ./frontend
    container_name: messenger_frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
