@startuml usecase-diagram
left to right direction
actor Не_авторизированный_пользователь as User1
actor Авторизованный_Пользователь as User
actor Администратор as Admin

rectangle TeamForge {
  (Регистрация) as UC1
  (Вход) as UC9
  (Отправка сообщения) as UC2
  (Присоединение к звонку) as UC3
  (Управление задачами) as UC4
  (Поиск в базе знаний) as UC5
  (Обращение к AI-ассистенту) as UC6
  (Управление каталогом ПО) as UC8
}

User -- UC2
User -- UC3
User -- UC4
User -- UC5
User -- UC6
Admin -- UC8
User1 -- UC1
User1 -- UC9
@enduml
